version: '3.9'
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html

  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./laravel:/var/www/html

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./next:/app
    command: sh -c "npm run dev"
    ports:
      - 3000:3000

  db:
    container_name: db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

volumes:
  db-volume:
